Feature: Uniform top menu
Snapmaker/Luban pull request #1033
Opened 2021-06-21 09:06 UTC by xiekun1992

[LU-836](https://snapmaker2.atlassian.net/browse/LU-836)

2021-06-22 08:10 UTC, meiliang1123 requested changes

2021-06-22 08:10 UTC, meiliang1123 commented on src/main.js
> -
remember to revert useless changes

2021-06-24 03:11 UTC, meiliang1123 requested changes

2021-06-25 02:31 UTC, parachvte commented on src/app/config/menu/editMenu.js
> +                    if (this.enabled) {
What does `this.enabled` means, why not check `this.enabled` in Electron?

2021-06-25 02:32 UTC, parachvte commented on src/app/config/menu/index.js
> +    if (isElectron() && window.require('electron').remote.process.platform === 'darwin') {
Add a comment pls.

2021-06-25 02:34 UTC, parachvte commented on src/app/constants/index.js
> +export const SUPPORT_ZH = 'https://support.snapmaker.com/hc/zh-cn';
Unify naming of URLs?

2021-06-25 02:41 UTC, parachvte commented on src/app/ui/Pages/AppBar/Menu.jsx
> +        activeMenu: PropTypes.func,
`isRequired`?

2021-06-25 02:45 UTC, parachvte commented on src/app/flux/topbar-menu/index.js
> +        actions.updateMenu()(dispatch);
`dispatch(actions.updateMenu())`?

2021-06-25 02:46 UTC, parachvte commented on src/app/flux/topbar-menu/index.js
> +    activeMenu: (index) => (dispatch, getState) => {
activate?

2021-06-25 02:47 UTC, parachvte commented on src/app/flux/topbar-menu/index.js
> +            state: topbarMenu
Will this cause a shallow compare that components are not being re-rendered?

2021-06-25 02:49 UTC, parachvte commented on src/app/flux/topbar-menu/index.js
> +let menuDisabledCount = 0;
Doubt it's proper way that `menuDisabledCount` is not placed in state.

When should we use this approach, even with redux?

2021-06-25 02:50 UTC, parachvte commented on src/app/flux/topbar-menu/index.js
> +let menuDisabledCount = 0;
Maybe the folder is better named `appbar-menu`?

2021-06-25 02:51 UTC, parachvte commented on src/app/lib/redux-middleware.js
> +export function topbarMenuMiddleware() {
Alright I got it.

2021-06-25 02:52 UTC, parachvte commented on src/app/lib/redux-middleware.js
> +                        clearTimeout(timer);
You don't have to call `clearTimeout`?

2021-06-25 02:52 UTC, parachvte commented on src/app/ui/App.jsx
> +// import { actions as projectActions } from '../flux/project';
Remove them if not needed.

2021-06-25 02:56 UTC, parachvte commented on src/app/ui/Pages/Header/Menu.jsx
> +import React, { PureComponent } from 'react';
Check if it's being used?

2021-06-25 03:00 UTC, parachvte requested changes
- Check if folder `src/app/ui/Pages/SettingsMenu` is being used
- Check if folder `src/app/ui/Pages/Header` is being used
- Rename `Pages` to `pages` and `Layouts` to `layouts` @meiliang1123

2021-06-25 06:53 UTC, xiekun1992 commented on src/app/lib/redux-middleware.js
> +export function topbarMenuMiddleware() {
What does this mean?

2021-06-25 06:53 UTC, xiekun1992 commented on src/app/lib/redux-middleware.js
> +export function topbarMenuMiddleware() {
> Alright I got it.
What does this mean?

2021-06-25 06:54 UTC, xiekun1992 commented on src/app/lib/redux-middleware.js
> +export function topbarMenuMiddleware() {
> Alright I got it.

What does this mean?

2021-06-25 06:59 UTC, xiekun1992 commented on src/app/flux/topbar-menu/index.js
> +            state: topbarMenu
> Will this cause a shallow compare that components are not being re-rendered?

A new menu array will be created in reducer and it will lead to a re-render

2021-06-25 07:00 UTC, xiekun1992 commented on src/app/flux/topbar-menu/index.js
> +    activeMenu: (index) => (dispatch, getState) => {
> activate menu?

Should I change the method name?

2021-06-25 11:07 UTC, merged