Feature: Add undo & redo
Snapmaker/Luban pull request #1062
Opened 2021-07-15 10:26 UTC by xiekun1992

[LU-1030](https://snapmaker2.atlassian.net/browse/LU-1030)

2021-07-16 02:14 UTC, parachvte commented on src/app/flux/index.js
> +    operationHistory
editor -> operationHistory?

2021-07-16 02:25 UTC, parachvte commented on src/app/flux/editor/actions-process.js
> +        operations.push(operation);
Just call `operation.redo()`?

It will call both

- `toolPathGroup.deleteToolPath(toolPathId);`
- `processActions.showSimulationInPreview(headType, false))`??

2021-07-16 02:27 UTC, parachvte commented on src/app/flux/operation-history/Operation.js
> +        console.log('redo');
`Operation` is an interface.

Just throw a `NotImplementedException`?

2021-07-16 02:27 UTC, parachvte commented on src/app/flux/operation-history/OperationHistory.js
> +        console.log(this.history);
Mind your console logs

2021-07-16 02:30 UTC, parachvte commented on src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
> +        this.props.modelGroup.on('add', this.actions.recordAddOperation);
off?

2021-07-16 05:11 UTC, parachvte requested changes
- location of `OperationHistory`, should it be an object on every editor?
- Implementation of operation in flux action, are there 2 kinds of actions (1 for user interaction action, 1 for real object operation)?

2021-07-16 05:12 UTC, parachvte commented on src/app/flux/index.js
> +    operationHistory
operationHistory is an object on every editor

2021-07-16 08:56 UTC, xiekun1992 commented on src/app/flux/editor/actions-process.js
> +        operations.push(operation);
`processActions.showSimulationInPreview(headType, false))` will change the `showSimulation` value, which is not the state of `toolpath`. I have communicated with PM that the simulation state does not need to undo or redo.

2021-07-16 08:59 UTC, xiekun1992 commented on src/app/flux/index.js
> +    operationHistory
Accept, refactoring is on the way.

2021-07-16 09:01 UTC, xiekun1992 commented
> * location of `OperationHistory`, should it be an object on every editor?
> * Implementation of operation in flux action, are there 2 kinds of actions (1 for user interaction action, 1 for real object operation)?

Refactoring...

2021-07-20 09:56 UTC, parachvte commented on src/app/flux/editor/index.js
> +                toolPaths: toolPathGroup.toolPaths.filter((item) => {
Why remove selected model, tool path is needed?

2021-07-20 09:57 UTC, parachvte commented on src/app/flux/editor/index.js
> +            target: model,
What's model?

2021-07-20 10:00 UTC, parachvte approved these changes

2021-07-20 11:20 UTC, merged