Refactor: Change laser cnc hooks
Snapmaker/Luban pull request #1175
Opened 2021-08-23 09:12 UTC by bbaa77770

2021-08-24 07:03 UTC, parachvte commented on src/app/ui/layouts/AppLayout.jsx
> +            this.props.exportFile(gcodeFile.uploadName);
`gcodeFile = stateHeadType` is a string? How can you call `gcodeFile.uploadName`?

2021-09-03 02:43 UTC, meiliang1123 requested changes

2021-09-03 03:32 UTC, jane-rose commented on src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
> +    }
outside

2021-09-03 03:32 UTC, jane-rose commented on src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
> +    }
extra conditional judgment

2021-09-03 04:28 UTC, merged