Refactor: Refactor to change class components related 3D printing to hooks
Snapmaker/Luban pull request #1176
Opened 2021-08-24 10:33 UTC by jane-rose

2021-09-02 02:45 UTC, xiekun1992 approved these changes

2021-09-02 06:14 UTC, meiliang1123 requested changes

2021-09-03 04:13 UTC, jane-rose commented on src/app/ui/components/Confirm/index.jsx
>      <button
no more use

2021-09-03 04:13 UTC, jane-rose commented on src/app/ui/widgets/PrintingVisualizer/VisualizerInfo.jsx
> +const GcodeInfo = () => {
no

2021-09-03 04:14 UTC, merged