Feature add material color selector
Snapmaker/Luban pull request #1227
Opened 2021-10-12 07:55 UTC by bbaa77770

2021-11-25 06:34 UTC, jane-rose approved these changes

2021-11-25 06:34 UTC, jane-rose commented on src/app/flux/printing/index.js
> +                        color: activeDefinition.settings.color.default_value
default color

2021-12-23 08:29 UTC, jane-rose commented on src/app/flux/printing/index.js
> +
Distinguish between single head and double head？

2021-12-23 08:29 UTC, jane-rose commented on src/server/slicer/slice.js
> +    console.log(args.join(' '));
log

2021-12-23 09:59 UTC, xiekun1992 requested changes

2021-12-23 09:59 UTC, xiekun1992 commented on src/app/ui/views/ProfileManager/SettingItem.jsx
> +                            style={{
use `class`

2021-12-23 09:59 UTC, xiekun1992 commented on src/app/ui/widgets/PrintingMaterial/MaterialWithColor.jsx
> +                style={{
use `class`

2021-12-23 09:59 UTC, xiekun1992 commented on src/app/models/ThreeModel.js
> +        this.updateMaterialColor(modelInfo.color ?? '#cecece');
use constant?

2021-12-28 07:28 UTC, jane-rose commented on src/app/ui/views/ProfileManager/index.jsx
> +            checkboxAndSelectGroup.color = d?.settings?.color?.default_value;
default_value could't use `?.`

2021-12-28 07:28 UTC, jane-rose commented on src/app/flux/manager/DefinitionManager.js
> +            const supportLineWidth = extruderLDefinitionSettings.machine_nozzle_size.default_value; // support_line_width
just using `extruderLDefinitionSettings`?

2021-12-28 07:28 UTC, jane-rose commented on src/app/flux/manager/DefinitionManager.js
> +
remove it

2021-12-28 13:06 UTC, merged

2022-01-07 07:23 UTC, parachvte commented on src/server/slicer/slice.js
> +    console.log(args.join(' '));
No resolved but PR merged?