Improvement: Improve workspace state values2
Snapmaker/Luban pull request #1271
Opened 2021-11-09 09:47 UTC by bbaa77770

LU-1708

2021-11-09 11:39 UTC, xiekun1992 commented on src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
> +                this.previewPrintableArea && this.state.printableArea.updateSize({
this.previewPrintableArea =>this.state.printableArea

2021-11-10 03:35 UTC, meiliang1123 requested changes

2021-11-10 03:35 UTC, meiliang1123 commented on src/app/flux/workspace/index.js
> +    toolHead: '',
workspace uses connected machine, should save headtype in flux/machine

2021-11-10 03:35 UTC, meiliang1123 commented on src/app/ui/widgets/Connection/SerialConnection.jsx
> +        } else if (machineHeadType === '10w-laser') {
split machineHeadType and machineToolHead

2021-11-10 03:35 UTC, meiliang1123 commented on src/app/ui/widgets/Marlin/Marlin.jsx
> +            {(headType === HEAD_PRINTING || headType === '3dp') && <Printing />}
why headType value has 2 value, should fix this bug.

2021-11-10 10:57 UTC, merged