Improvement: Add laser 10w security code for serial port
Snapmaker/Luban pull request #1328
Opened 2021-12-01 09:59 UTC by bbaa77770

2021-12-01 13:51 UTC, xiekun1992 requested changes

2021-12-01 13:51 UTC, xiekun1992 commented on src/server/controllers/Marlin/Marlin.js
> +        const r1 = line.match(/^security_state: ([0-9]),.*$/);
leave an example about how the regular express works

2021-12-02 09:20 UTC, xiekun1992 approved these changes

2021-12-02 09:34 UTC, jane-rose approved these changes

2021-12-13 03:48 UTC, jane-rose commented
Need to merge on v4.1.2

2022-01-10 09:50 UTC, merged