Feature: Add dual printing material settings
Snapmaker/Luban pull request #1344
Opened 2021-12-09 12:29 UTC by bbaa77770

2021-12-10 03:55 UTC, xiekun1992 commented on resources/CuraEngine/Config/printing/snapmaker_extruder_0.def.json
> +        "position": "1"
`position` should be `"0"`

2021-12-10 04:29 UTC, xiekun1992 requested changes

2021-12-10 04:29 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +    updateDefaultConfigId: (type, defaultId, direction = 'left') => (dispatch, getState) => {
`'left'` => `LEFT_EXTRUDER` ?

2021-12-10 04:29 UTC, xiekun1992 commented on package.json
> +    "ant-design": "^1.0.0",
icons should be provided by UI designer, remove this dependency

2021-12-10 04:29 UTC, xiekun1992 commented on src/app/ui/views/PrintingManager/PrintingManager.jsx
> +    const printingMaterialConfigKeys = (toolHead.printingToolhead === SINGLE_EXTRUDER_TOOLHEAD_FOR_SM2 ? PRINTING_MATERIAL_CONFIG_KEYS_SINGLE : PRINTING_MATERIAL_CONFIG_KEYS_DUAL);
combine these with a `if` statement

2021-12-13 06:39 UTC, jane-rose commented on src/app/ui/widgets/PrintingMaterial/Material.jsx
> +        { value: 0.6, label: 0.6 }
move `constans` outside the component

2021-12-14 07:57 UTC, jane-rose commented on src/app/ui/widgets/PrintingMaterial/Material.jsx
> +                            className="height-32"
Number input?

2021-12-17 07:06 UTC, xiekun1992 approved these changes

2021-12-17 07:09 UTC, merged