Feature: Add align function for 3DP
Snapmaker/Luban pull request #1346
Opened 2021-12-10 06:59 UTC by jane-rose

2021-12-20 11:44 UTC, xiekun1992 requested changes

2021-12-20 11:44 UTC, xiekun1992 commented on src/app/flux/operation-history/GroupAlignOperation3D.ts
> +    selectedModelsPositionMap: Map<string, any>
can `PositionObject` replace `any` ?

2021-12-21 04:28 UTC, wen-qing-255 approved these changes

2021-12-21 07:01 UTC, bbaa77770 approved these changes

2021-12-21 07:11 UTC, merged