Static front end packaging
Snapmaker/Luban pull request #1354
Opened 2021-12-15 10:54 UTC by jane-rose

2021-12-20 10:34 UTC, xiekun1992 requested changes

2021-12-20 10:34 UTC, xiekun1992 commented on src/server/app.js
> +            console.log('webroot', webroot);
log remove

2021-12-20 10:34 UTC, xiekun1992 commented on src/server/app.js
> +        app.get(urljoin(settings.route, '/'), renderPage('index.hbs', (req) => {
use a variable to specify `index.hbs` or `index.html`

2021-12-20 10:34 UTC, xiekun1992 commented on src/server/slicer/definition.js
> +    const regex = /^material.([A-Za-z0-9_]+).([A-Za-z0-9_]+?).def.json$/;
@wen-qing-255 check this please

2021-12-21 06:10 UTC, wen-qing-255 commented on src/server/slicer/definition.js
> +    const regex = /^material.([A-Za-z0-9_]+).([A-Za-z0-9_]+?).def.json$/;
the thrid '.' is not necessary.

2021-12-21 06:33 UTC, wen-qing-255 approved these changes

2021-12-21 06:34 UTC, wen-qing-255 commented on src/server/slicer/definition.js
> +    const regex = /^material.([A-Za-z0-9_]+).([A-Za-z0-9_]+?).def.json$/;
const regex = /^material.([A-Za-z0-9_]+).([A-Za-z0-9_.]+?)def.json$/;   use this

2021-12-21 06:41 UTC, parachvte requested changes
Changes required.

2021-12-21 06:41 UTC, parachvte commented on package-lock.json
> +        "snapmaker-react-icon": "~1.19.5",
Use fixed version when using icon. Or make sure your patches are compatible.

2021-12-21 06:41 UTC, parachvte commented on src/main.js
> +    // If needed, resolve CORS. https://stackoverflow.com/questions/51254618/how-do-you-handle-cors-in-an-electron-app
Remove testing code before merge.

2021-12-21 06:41 UTC, parachvte commented on src/server/app.js
> +        app.get(urljoin(settings.route, '/'), renderPage('index.hbs', (req) => {
+1

2021-12-21 06:41 UTC, parachvte commented on src/server/slicer/definition.js
> +    const regex = /^material.([A-Za-z0-9_]+).([A-Za-z0-9_]+?).def.json$/;
Correct use of .

2021-12-21 06:41 UTC, parachvte commented on webpack.config.app.production.js
> +// const publicPath = (function calculatePublicPath(payload) {
Check why we need to add hash string to public path.

I think it's needed even in production release. @xiekun1992 @jane-rose

2021-12-21 06:54 UTC, jane-rose commented on package-lock.json
> +        "snapmaker-react-icon": "~1.19.5",
Patches are compatible.

2021-12-21 07:17 UTC, xiekun1992 commented on webpack.config.app.production.js
> +// const publicPath = (function calculatePublicPath(payload) {
@parachvte There is an example: `http://127.0.0.1:53000/3ba1cdcd/app.55cfbcc1ea61a6de07dd.bundle.js?_=1639624130562` and `3ba1cdcd` is the `publicPath`. Actually the file name does the same thing, that is skipping cache. Other resources file like images load from a different path, such as `http://127.0.0.1:53000/resources/images/user-case/Origin/library_fabric_97x97.png`, they don't share the same path, so it can be removed.

2021-12-29 08:11 UTC, xiekun1992 requested changes

2021-12-29 08:11 UTC, xiekun1992 commented on src/app/models/SvgModel.js
> +            console.log('uploadPath', uploadPath);
remove log

2021-12-29 08:11 UTC, xiekun1992 commented on src/main.js
> +import parse from 'url-parse';
consider to use nodejs [URL module](https://nodejs.org/dist/latest-v16.x/docs/api/url.html)

2021-12-29 09:29 UTC, merged