Feature: Add prime tower
Snapmaker/Luban pull request #1373
Opened 2021-12-26 11:47 UTC by wen-qing-255

2021-12-28 02:47 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +            console.log({ transformation });
remove log

2021-12-28 03:29 UTC, xiekun1992 requested changes

2021-12-28 03:29 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +        return this.selectedModelArray.length === 1 && this.selectedModelArray.every((model) => {
`this.selectedModelArray.every` can simplify to `this.selectedModelArray[0]`

2021-12-28 03:29 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +        const modelTemp = _.cloneDeep(this.models);
unnecessary to use `cloneDeep`, because you only read their properties

2021-12-28 03:29 UTC, xiekun1992 commented on src/app/models/PrimeTowerModel.ts
> +    // meshObject: THREE.Object3D;
explicitly declare class properties

2021-12-28 03:29 UTC, xiekun1992 commented on src/app/models/ThreeModel.js
> +        this.primeTowerTag = primeTowerTag;
`primeTowerTag` belongs to `PrimeTowerModel`, remove it from `ThreeModel` and assign it in `PrimeTowerModel`

2021-12-28 03:29 UTC, xiekun1992 commented on src/app/models/ThreeModel.js
> +        if (isSelected && this.primeTowerTag && this.meshObject.geometry._bufferGeometry?.getAttribute('color')) {
what does it do? is it duplicated?

2021-12-28 03:56 UTC, jane-rose commented on src/app/models/ModelGroup.js
> +                    if (this.selectedModelArray.length && this.selectedModelArray[0].primeTowerTag !== model.primeTowerTag) {
Check this condition?

2021-12-28 03:56 UTC, jane-rose commented on src/app/models/ThreeModel.js
> +            scale.x = scale.y;
why?

2021-12-28 03:56 UTC, jane-rose commented on src/app/ui/components/SMCanvas/TransformControls.js
> +        // ]);
Delete logs

2021-12-28 03:56 UTC, jane-rose commented on src/app/ui/components/SMCanvas/TransformControls.js
> +                        parentEVec.y = this.axis === 'X' ? parentEVec.x : parentEVec.y;
Why revert x and y

2021-12-29 09:11 UTC, xiekun1992 approved these changes

2021-12-29 09:33 UTC, merged