Fix: Fix UI error in gcode line review
Snapmaker/Luban pull request #1393
Opened 2022-01-04 11:28 UTC by bbaa77770

2022-01-11 09:47 UTC, MaShizhen commented on src/app/flux/printing/index.js
> +    ALIGN_OPERATION
> ```ALIGN_OPERATION``` 

This variable is often changed recently. It is better to rebase the master

2022-01-11 09:47 UTC, MaShizhen commented on src/app/styles/global-edge-distance.styl
> + margin-left: $px-grade-n-4;
Indent should be unified

2022-01-11 09:47 UTC, MaShizhen commented on src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
> +                                                                content: i18n._('key-Printing/Preview-Tool0'),
It is suggested to change to `'key-Printing/Preview-Extruder L'`

2022-01-11 09:47 UTC, MaShizhen commented on src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
> +    const lineTypeObjects0 = [
ExtruderLineType ?
structureLineType ?

2022-01-17 09:42 UTC, jane-rose commented on src/app/ui/components/ColorSelector/ColorSelectorWrapper.jsx
> +            localStorage.setItem(`color-selector-${recentColorKey}`, newRecentColors);
use `storeManager` not `localStorage`

2022-01-17 09:42 UTC, jane-rose commented on src/app/ui/views/ProfileManager/SettingItem.jsx
> +                        recentColorKey="profile-manager"
constant

2022-01-17 09:42 UTC, jane-rose commented on src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
> +    const lineTypeObjects0 = [
+1，change name

2022-01-17 09:57 UTC, xiekun1992 requested changes

2022-01-17 09:57 UTC, xiekun1992 commented on src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
> +                                        {renderLineType && (lineTypeObjects1.map((obj) => {
use a good name for `lineTypeObjects1` and `lineTypeObjects0`

2022-01-18 12:29 UTC, jane-rose commented on src/app/store/local-storage.js
> -        return _.merge(machineStore.get(), widgetStore.get());
missing init `components.json` on `userData` object

2022-01-19 03:23 UTC, merged