Improvement: Preview file when import G code to workspace
Snapmaker/Luban pull request #1404
Opened 2022-01-11 09:06 UTC by MaShizhen

2022-01-20 11:10 UTC, xiekun1992 requested changes

2022-01-20 11:10 UTC, xiekun1992 commented on src/app/ui/widgets/WifiTransport/WifiTransport.jsx
> +                    setTimeout(() => {
leave a comment to explain why you need a `setTimeout`

2022-01-21 02:10 UTC, jane-rose approved these changes

2022-01-21 02:10 UTC, jane-rose commented on src/app/ui/widgets/WifiTransport/WifiTransport.jsx
> +                    setTimeout(() => {
Remove it

2022-01-21 02:12 UTC, merged