Improvement: Improvement prime tower
Snapmaker/Luban pull request #1421
Opened 2022-01-18 12:10 UTC by wen-qing-255

2022-01-19 09:51 UTC, jane-rose commented on src/app/flux/printing/index.js
> +            const modelGroupBBox = modelGroup._bbox;
just use `new Three.Box3 `

2022-01-19 11:01 UTC, wen-qing-255 commented on src/app/flux/printing/index.js
> +            const modelGroupBBox = modelGroup._bbox;
never modify modelGroupBBox，need platform boundingbox to get prime tower position.

2022-01-20 03:11 UTC, xiekun1992 requested changes

2022-01-20 03:11 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +            const primeTowerModel = lodashFind(modelGroup.getModels(), { type: 'primeTower' });
consider to define a method in `modelGroup` to filter out specific sub models

2022-01-20 03:11 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +                const models = modelGroup.models.filter(i => i.visible && i.type !== 'primeTower').reduce((pre, model) => {
consider to define a method in `modelGroup` to filter out specific sub models

2022-01-20 03:11 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +        const models = filter(modelGroup.getModels(), (modelItem) => {
consider to define a method in `modelGroup` to filter out specific sub models

2022-01-20 03:12 UTC, bbaa77770 commented on src/app/flux/printing/index.js
> +            activeDefinition.settings.prime_tower_wipe_enabled.default_value = true;
Why is always true

2022-01-20 03:16 UTC, jane-rose approved these changes

2022-01-20 03:16 UTC, jane-rose commented on src/app/flux/printing/index.js
> +        });
add function inside modelGroup to filter models

2022-01-20 03:18 UTC, merged