Fix: Fix 3dp profile category operation support bugs
Snapmaker/Luban pull request #1437
Opened 2022-02-07 07:30 UTC by MaShizhen

2022-02-10 11:30 UTC, jane-rose commented on src/app/ui/views/ProfileManager/index.jsx
> +                    currentDefinition.category || i18n._('key-default_category-Custom')
same here

2022-02-11 03:21 UTC, xiekun1992 requested changes

2022-02-11 03:21 UTC, xiekun1992 commented on src/app/lib/uni-api.js
> +                const txt = fs.readFileSync(tmpFile, 'utf-8');
`'utf-8'` -> `'utf8'`

2022-02-11 03:21 UTC, xiekun1992 commented on src/app/lib/uni-api.js
> +                    .get(`/data${tmpFile}`)
`/data` is the value of constant variable `DATA_PATH`, use `${DATA_PATH}${tmpFile}`

2022-02-11 03:21 UTC, xiekun1992 commented on src/app/lib/uni-api.js
> +                    .get(`/data${tmpFile}`)
`/data` is the value of constant variable `DATA_PATH`, use `${DATA_PATH}${tmpFile}`

2022-02-11 06:47 UTC, wen-qing-255 commented on src/app/flux/editor/actions-process.js
> +                        i18n._(definition.i18nName) || definition.name
why need to `|| definition.name` ?

2022-02-11 06:47 UTC, bbaa77770 approved these changes

2022-02-11 06:49 UTC, bbaa77770 reviewed
Try to reduce use 'i18nCategory'.

2022-02-11 06:53 UTC, MaShizhen commented on src/app/flux/editor/actions-process.js
> +                        i18n._(definition.i18nName) || definition.name
Avoid errors due to lack of I18N comparison

2022-02-11 07:22 UTC, wen-qing-255 commented on src/app/flux/editor/actions-process.js
> +                        i18n._(definition.i18nName) || definition.name
but i think i18n._() always return value

2022-02-11 07:28 UTC, MaShizhen commented
`i18nCategory` has some reading scenes
    - Category exists in profile file of old version, restore through I18N when importing
    - render ProfileManager CateList
    - The category of the exported profile is consistent with the current language

`i18nCategory`Set scene
    - copy default profile，keep the original i18ncategory
    - copy custom profile，clear i18ncategory

2022-02-11 07:28 UTC, MaShizhen commented on src/app/flux/editor/actions-process.js
> +                        i18n._(definition.i18nName) || definition.name
done

2022-02-11 07:29 UTC, MaShizhen commented on src/app/ui/views/ProfileManager/index.jsx
> +            if (i18nCategory === 'key-default_category-Custom') {
done

2022-02-15 04:02 UTC, xiekun1992 approved these changes

2022-02-15 09:26 UTC, jane-rose approved these changes

2022-02-15 09:28 UTC, merged