Improve thread poll
Snapmaker/Luban pull request #1444
Opened 2022-02-11 02:28 UTC by MaShizhen

2022-02-14 10:22 UTC, jane-rose approved these changes

2022-02-14 10:22 UTC, jane-rose commented on src/server/lib/SocketManager/index.ts
> +        this.io = new Server(this.server, {
Leave a comment

2022-02-16 03:58 UTC, xiekun1992 requested changes

2022-02-16 03:58 UTC, xiekun1992 commented on src/server/lib/MeshProcess/MeshProcess.js
> +import global from '../global';
it is better not use `global` as variable name, just like `window` in browser, `global` is the root context for `node.js`, see: [Global objects](https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#global)

2022-02-16 03:58 UTC, xiekun1992 commented on src/server/lib/MeshProcess/STLToSvgStack.js
> +import global from '../global';
it is better not use `global` as variable name, just like `window` in browser, `global` is the root context for `node.js`, see: [Global objects](https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#global)

2022-02-16 03:58 UTC, xiekun1992 commented on src/server/lib/editor/image-process.js
> +import global from '../global';
it is better not use `global` as variable name, just like `window` in browser, `global` is the root context for `node.js`, see: [Global objects](https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#global)

2022-02-16 04:28 UTC, jane-rose commented on src/server/lib/editor/image-process.js
> +import global from '../global';
merge it now, change it later

2022-02-16 04:28 UTC, merged

2022-02-16 04:29 UTC, jane-rose commented
https://snapmaker2.atlassian.net/browse/LU-2135

2022-02-18 09:35 UTC, MaShizhen commented on src/server/lib/MeshProcess/MeshProcess.js
> +import global from '../global';
https://github.com/Snapmaker/Luban/pull/1460/files

2022-02-18 09:36 UTC, MaShizhen commented on src/server/lib/editor/image-process.js
> +import global from '../global';
https://github.com/Snapmaker/Luban/pull/1460/files