Feature: Refactor printing leftbar & Improve rotate feature
Snapmaker/Luban pull request #1503
Opened 2022-03-10 06:54 UTC by wen-qing-255

2022-03-17 03:52 UTC, xiekun1992 requested changes

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +        setTimeout(() => {
auto rotation is moved to web worker, is `setTimeout` still necessary?

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +        setTimeout(() => {
make sure if `setTimeout` here and below still necessary

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/models/ThreeModel.js
> +        console.log({ center, x, y, z });
remove log

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/models/ThreeModel.js
> +        // console.log(this.transformation);
remove it

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/models/ThreeModel.js
> +        console.log({ normal: targetPlane.normal, xyPlaneNormal, newQuaternion });
remove log

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/TransformControls.js
> +        // this.leftPlane = this.createPeripheral([
remove it

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/TransformControls.js
> +                // const boundingBoxWidth = maxObjectBoundingBox.y - minObjectBoundingBox.y;
remove comments

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/TransformControls.js
> +            // if (this.hoverFace === 'left') {
remove comments here and below

2022-03-17 03:52 UTC, xiekun1992 commented on src/app/ui/pages/Printing.jsx
> +            window.removeEventListener('update-rotate', ({ detail }) => {
will this unregister work by passing different callback function?

2022-03-17 07:27 UTC, jane-rose commented on src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
> +                            allowUndefined
why this 'input' value can be `null`?

2022-03-17 07:28 UTC, jane-rose commented on src/app/ui/pages/Printing.jsx
> +            window.removeEventListener('update-rotate', ({ detail }) => {
+1

2022-03-18 09:50 UTC, wen-qing-255 commented on src/app/models/ModelGroup.js
> +    getModels(filterKey = '') {
other place also use this function, can not modify

2022-03-18 10:02 UTC, wen-qing-255 commented on src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
> +                            allowUndefined
because this input has sometime need be null，see the original status

2022-03-21 07:34 UTC, wen-qing-255 commented on src/app/flux/printing/index.js
> +        setTimeout(() => {
here still need, if delete the `setTimeout` , the progressBar cannot show

2022-03-24 06:24 UTC, jane-rose commented
https://snapmaker2.atlassian.net/browse/LU-2130

2022-04-07 07:43 UTC, xiekun1992 requested changes

2022-04-07 07:43 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +    // startAutoRotateSelectedModelProgess: () => (dispatch, getState) => {
add unused code? can be removed?

2022-04-07 07:43 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +        setTimeout(() => {
alright

2022-04-07 07:43 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +        console.log('this.selected', this.selectedGroup);
remove this line

2022-04-07 07:43 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/Canvas.jsx
> +                inputDOM = document.getElementById('rotate-input-control');
this may not be `React` way

2022-04-07 07:43 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/Canvas.jsx
> +            if (this.controls.transformControl.mode !== 'rotate' || !this.modelGroup.selectedModelArray.length || (this.modelGroup.selectedModelArray.length && some(this.modelGroup.selectedModelArray
add an API `hasVisibleModel()` instead of  `(this.modelGroup.selectedModelArray.length && some(this.modelGroup.selectedModelArray, { visible: false })`

2022-04-07 07:43 UTC, xiekun1992 commented on src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
> +    const hasHideModel = every(selectedModelArray, { visible: false }) && selectedModelArray.length;
extract this line to an API for `modelGroup`

2022-04-07 12:24 UTC, jane-rose approved these changes

2022-04-07 12:29 UTC, merged