Improvement: Improvement svg curve draw
Snapmaker/Luban pull request #1505
Opened 2022-03-10 08:48 UTC by MaShizhen

2022-03-17 03:33 UTC, xiekun1992 requested changes

2022-03-17 03:33 UTC, xiekun1992 commented on src/app/flux/editor/index.js
> +        console.log('>> generateModel');
remove log

2022-03-17 03:33 UTC, xiekun1992 commented on src/app/flux/operation-history/index.js
> +        history.history = history.history.filter((item) => {
do not edit access `history.history` directly, expose API from `OperationHistory`

2022-03-17 03:33 UTC, xiekun1992 commented on src/app/models/SvgModel.js
> +                    elem.setAttribute('x', (bbox.x + bbox.width / 2).toString());
use ES6 Template Strings

2022-03-17 03:33 UTC, xiekun1992 commented on src/app/ui/SVGEditor/svg-content/DrawGroup/DrawGroup.ts
> +    private compD() {
use a full name

2022-03-17 03:33 UTC, xiekun1992 commented on src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
> +            this.onDrawLine(line);
declare `onDrawXXX` methods explicitly, these methods area dynamically assigned which can be confused

2022-04-09 11:53 UTC, jane-rose commented on src/app/flux/editor/index.js
> +        const { SVGActions, SVGCanvasMode, SVGCanvasExt } = getState()[headType];
Option: disable select all element shorcut when in draw mode

2022-04-13 03:59 UTC, xiekun1992 requested changes

2022-04-13 03:59 UTC, xiekun1992 commented on src/app/flux/laser/index.js
> +                const ll = Object.assign({}, state, { ...action.state });
restore this after debug

2022-04-13 03:59 UTC, xiekun1992 commented on src/shared/lib/utils.js
> +import { JudgeMoveMiniDistance } from '../../app/constants';
`JudgeMoveMiniDistance` => `JUDGE_MOVE_MINI_DISTANCE`

2022-04-13 03:59 UTC, xiekun1992 commented on src/app/ui/SVGEditor/svg-content/DrawGroup/CursorGroup.ts
> +        cursor.innerHTML = `
refer: [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor), use CSS to modify cursor

2022-04-13 09:06 UTC, merged