Improvement: Improve gcode preview
Snapmaker/Luban pull request #1520
Opened 2022-03-18 08:48 UTC by bbaa77770

2022-03-29 06:42 UTC, xiekun1992 requested changes

2022-03-29 06:42 UTC, xiekun1992 commented on src/app/flux/printing/index.js
> +            const s = Object.assign({}, state, action.state);
restore this

2022-03-29 06:42 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +        this.models.forEach(model => {
including Prime Tower?

2022-03-29 06:42 UTC, xiekun1992 commented on src/app/ui/widgets/PrintingVisualizer/ModeToggleBtn.jsx
> +                                        style={{ margin: '16px', marginRight: '10px' }}
define a CSS class?

2022-03-29 06:42 UTC, xiekun1992 commented on src/app/ui/widgets/PrintingVisualizer/ModeToggleBtn.jsx
> +                                            <span style={{ fontSize: '14px' }} className="v-align-m margin-left-8">
use CSS class for `fontSize: '14px'`

2022-03-29 06:42 UTC, xiekun1992 commented on src/app/workers/GcodeToBufferGeometry/gcodeBufferGeometryToObj3d.js
> +            console.log('gcodeBufferGeometryToObj3d');
remove log

2022-04-09 04:17 UTC, jane-rose commented
Closed since it's not ready.

2022-04-09 04:17 UTC, closed without merging