Feature: Add fitViewIn in context menu 3dp
Snapmaker/Luban pull request #1538
Opened 2022-04-09 08:16 UTC by bbaa77770

[LU-2243](https://snapmaker2.atlassian.net/browse/LU-2243)

2022-04-09 09:43 UTC, jane-rose commented on src/app/ui/components/SMCanvas/Canvas.jsx
> +        const o1 = { x: this.camera.position.x, y: this.camera.position.y, z: this.camera.position.z };
just `o1 = this.camera.position` ?

2022-04-12 13:12 UTC, jane-rose approved these changes

2022-04-12 13:12 UTC, jane-rose commented on src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
> +                this.props.modelGroup.unselectAllModels();
remove duplicate code

2022-04-13 03:05 UTC, xiekun1992 requested changes

2022-04-13 03:05 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/Canvas.jsx
> +    fitViewIn(center, r) {
make variable name more meaningful

2022-04-13 08:38 UTC, merged