Improvement: Improvement 3dp left toolbar unified
Snapmaker/Luban pull request #1542
Opened 2022-04-09 10:34 UTC by MaShizhen

2022-04-09 10:45 UTC, wen-qing-255 commented on src/app/models/ModelGroup.js
> -    hasHideModel() {
why delete this function?

2022-04-09 10:54 UTC, wen-qing-255 commented on src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
> +                        disabled={selectedModelArray.length > 0 && !isSelectedModelAllVisible}
Auto rotate disabled when all model are hidden.

2022-04-09 10:55 UTC, wen-qing-255 commented on src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
> +                        disabled={selectedModelArray.length > 0 && !isSelectedModelAllVisible}
We cannot delete `modelGroup.allIsHideModel`

2022-04-09 11:04 UTC, wen-qing-255 commented on src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
> +    const transformDisabled = showRotationAnalyzeModal || showEditSupportModal || !hasModels;
why only selected primeTower will be transformDisabled status

2022-04-11 02:35 UTC, xiekun1992 requested changes

2022-04-11 02:35 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +        return this.selectedModelArray.every(model => model.visible && !(model instanceof PrimeTowerModel));
consider to use `type`, eg: `this.modelGroup.selectedModelArray[0].type !== 'primeTower'`

2022-04-11 02:35 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +                    if (this.selectedModelArray.length === 1 && this.selectedModelArray[0] instanceof PrimeTowerModel) {
consider to use `type`, eg: `this.modelGroup.selectedModelArray[0].type !== 'primeTower'`

2022-04-11 02:35 UTC, xiekun1992 commented on src/app/ui/components/SMCanvas/TransformControls.js
> +        console.log('isPrimeTower =', isPrimeTower);
remove

2022-04-12 08:23 UTC, jane-rose commented on src/app/ui/widgets/PrintingVisualizer/Overlay/ExtruderOverlay.jsx
> +            <div className="sm-flex justify-space-between margin-left-16 width-160 border-default-black-5 border-radius-8 padding-vertical-4 padding-left-8" style={disabled ? { background: '#f5f5f5',
use default className

2022-04-13 02:24 UTC, xiekun1992 approved these changes

2022-04-13 02:24 UTC, xiekun1992 commented on src/app/ui/widgets/PrintingVisualizer/Overlay/ExtruderOverlay.jsx
> +            <div className="sm-flex justify-space-between margin-left-16 width-160 border-default-black-5 border-radius-8 padding-vertical-4 padding-left-8" style={disabled ? { background: '#f5f5f5',
+1

2022-04-13 08:21 UTC, merged