Refactor: Add A400 Laser 10W camera capture workflow & manual connect WIFI
Snapmaker/Luban pull request #1575
Opened 2022-04-26 11:06 UTC by xiekun1992

[LU-2292](https://snapmaker2.atlassian.net/browse/LU-2292)

2022-04-27 06:39 UTC, wen-qing-255 commented
包括以下参数修改 https://snapmaker2.atlassian.net/browse/LU-2278

2022-04-27 07:02 UTC, MaShizhen requested changes

2022-04-27 07:02 UTC, MaShizhen commented on src/server/services/socket/SACP-TCP.ts
> +            const state: any = {
should be banned

2022-04-27 07:02 UTC, MaShizhen commented on src/server/services/socket/SACP-TCP.ts
> +            const result: any = {
should be banned

2022-04-27 10:23 UTC, xiekun1992 commented on src/server/lib/image-getPhoto.js
> +                resolve({
only debug info

2022-04-27 12:39 UTC, jane-rose approved these changes

2022-04-27 12:39 UTC, jane-rose commented on src/app/ui/widgets/WifiTransport/WifiTransport.jsx
> +    }, [workflowStatus]);
checkout this for now

2022-04-27 12:39 UTC, jane-rose commented on src/server/services/socket/ConnectionManager.js
> +        const PORT_SCREEN_HTTP = 8080, PORT_SCREEN_SACP = 8888;
make this a constant

2022-04-27 12:39 UTC, jane-rose commented on src/server/services/task-manager/workers/generateGcode.js
> +    console.log({ size });
log

2022-04-28 02:25 UTC, wen-qing-255 approved these changes

2022-05-09 03:45 UTC, merged