Refactor: Refactor to change the modify profile process and slicing process in 3dp
Snapmaker/Luban pull request #1593
Opened 2022-05-19 03:10 UTC by jane-rose

2022-05-19 10:16 UTC, xiekun1992 requested changes

2022-05-19 10:16 UTC, xiekun1992 commented on src/app/models/SvgModel.js
> +        this.uploadimagename = res.body.uploadname;
this renaming will cause some potential problems

2022-05-19 10:16 UTC, xiekun1992 commented on src/app/models/ModelGroup.js
> +            if (modelItem.headType === HEAD_PRINTING && !modelItem.supportTag) {
`!modelItem.supportTag` will always be `true`

2022-05-20 09:52 UTC, jane-rose commented on src/app/models/SvgModel.js
> +        this.uploadimagename = res.body.uploadname;
this will be fixed on other pr

2022-05-24 07:44 UTC, MaShizhen approved these changes

2022-05-24 12:18 UTC, jane-rose commented
https://snapmaker2.atlassian.net/browse/LU-2370

2022-05-24 12:19 UTC, merged