Feature add multiselect in 3dp
Snapmaker/Luban pull request #413
Opened 2020-08-14 02:20 UTC by jane-rose

2020-08-14 07:30 UTC, parachvte commented on src/app/flux/printing/index.js
> +    selectTargetModel: (model, shiftKey) => (dispatch, getState) => {
`shiftKey`, `multiSelect`

2020-08-14 07:34 UTC, parachvte commented on src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
> +
?

2020-08-14 07:43 UTC, parachvte commented on src/app/components/Input/NumberInput.jsx
> +        resettodefaultvalue: PropTypes.string,
boolean, camel case

2020-08-14 07:49 UTC, parachvte commented on src/app/components/SMCanvas/Controls.jsx
> +                     if (this.lastSelectedMultiObject && this.lastSelectedMultiObject.length === 1) {
is variable `lastSelectedMultiObject` necessary?

2020-08-14 07:57 UTC, parachvte commented on src/app/flux/models/ModelGroup.js
> +    selectModelById(modelID, shiftKey) {
`shiftKey` -> `multiSelect = false`

2020-08-25 10:12 UTC, meiliang1123 commented on src/app/flux/printing/index.js
> +    selectMultiModel: (selectedGroup) => (dispatch, getState) => {
suggest: implement  and trigger refresh in modelgroup.js

2020-08-25 10:12 UTC, meiliang1123 commented on src/app/flux/printing/index.js
> +        const modelState = modelGroup.selectModelById([model], isMultiSelect);
selecteModelById need an modelID, here is an array

2020-08-25 10:12 UTC, meiliang1123 commented on src/app/flux/printing/index.js
> +    getSelectedModelArray: () => (dispatch, getState) => {
suggest: we can get modelGroup attributes in connected components directly

2020-08-25 10:12 UTC, meiliang1123 commented on src/app/flux/printing/index.js
> +    selectAllModels: () => (dispatch, getState) => {
suggest: modelState is deprecated, map modelGroup attributes to refresh components

2020-08-26 03:18 UTC, parachvte commented on src/app/components/ProgressBar/index.jsx
> +            // this.timeout = setTimeout(() => this.setState({ display: 'none' }), 5000);
Remember to uncomment this line before merging.

2020-08-26 03:45 UTC, parachvte commented on src/app/components/SMCanvas/Controls.jsx
> +
?

2020-08-26 03:49 UTC, parachvte commented on src/app/components/SMCanvas/Controls.jsx
> -            case STATE.ROTATE:
Why remove this?

2020-08-26 04:01 UTC, parachvte commented on src/app/components/SMCanvas/Controls.jsx
> +    setModelGroup(modelGroup) {
Make an interface, not use modelGroup directly,

2020-08-26 04:02 UTC, parachvte commented on src/app/components/SMCanvas/TransformControls.js
> +// import * as THREE from 'three';
?

2020-08-26 04:03 UTC, parachvte commented on src/app/components/SMCanvas/TransformControls.js
> +    // selectObjectPosition = new Vector3();
remove unused code

2020-08-26 04:06 UTC, parachvte commented on src/app/components/SMCanvas/TransformControls.js
> +
?

2020-08-26 04:06 UTC, parachvte commented on src/app/components/SMCanvas/TransformControls.js
> +        // this.object = new Group();
?

2020-08-26 04:07 UTC, parachvte commented on src/app/flux/models/Model.js
> +
?

2020-08-26 06:33 UTC, parachvte commented on src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
> +                        modelGroup={{ object: this.visualizerGroup }}
Avoid re-creation of temporary objects.

2020-08-26 06:35 UTC, parachvte requested changes
Need fixes:
- rotation implementation
- context menu actions
- relation of `ModelGroup` and `Controls`

2020-08-31 05:13 UTC, merged