Improvement: Synchronise zoom action
Snapmaker/Luban pull request #440
Opened 2020-09-08 03:30 UTC by meiliang1123

- Synchronise zoom action between editor and process tab of laser / cnc
- Don't show cnc-warning popup on next open when warning label checked

2020-10-19 10:02 UTC, parachvte commented on src/app/components/SMCanvas/Canvas.jsx
> +            this.lastScale = nextProps.scale;
First lastScale update

2020-10-19 10:03 UTC, parachvte commented on src/app/components/SMCanvas/Canvas.jsx
> +            this.lastScale = currentScale;
Second lastScale update

We only need one?

2020-10-19 10:03 UTC, parachvte commented on src/app/components/SMCanvas/Canvas.jsx
> +    }
;

2020-10-19 10:03 UTC, parachvte commented on src/app/components/SMCanvas/Canvas.jsx
> +    }
;

2020-10-19 10:04 UTC, parachvte commented on src/app/components/SMCanvas/Canvas.jsx
> +        this.timeoutChangeTarget = setTimeout(() => {
Not elegant solution :(

2020-10-19 10:28 UTC, parachvte commented on src/app/components/SMCanvas/Controls.jsx
> +        if (this.scale !== 1) {
put it in L448?

2020-10-19 10:32 UTC, parachvte requested changes
This is not a good solution for zoom synchronization.

It works for now, and we will refactor it afterwards.

2020-10-20 03:04 UTC, meiliang1123 commented on src/app/components/SMCanvas/Canvas.jsx
> +        this.timeoutChangeTarget = setTimeout(() => {
changed to trigger on mouse up

2020-10-20 03:08 UTC, meiliang1123 commented on src/app/components/SMCanvas/Canvas.jsx
> +            this.lastScale = currentScale;
Set lastScale here to avoid update loop, app will crash if this line removed

2020-10-20 11:37 UTC, merged