Fix: Allow sidebars to scroll independently of main window
Snapmaker/Luban pull request #557
Opened 2020-11-13 11:27 UTC by jane-rose

2020-11-13 11:31 UTC, jane-rose commented
#500

2020-11-13 12:55 UTC, adamphillips commented
Is it worth removing `.primary-container` and `.secondary-container` from [here](https://github.com/Snapmaker/Luban/blob/78160f6ea26a4667d01d506e29ec757e8b7d3a39/src/app/containers/Workspace/index.styl#L13) as well now since these styles will always be overridden?

2020-11-16 02:18 UTC, parachvte requested changes

2020-11-16 02:18 UTC, parachvte commented on src/app/widgets/Console/Terminal.jsx
> +        setTimeout(() => {
Add a comment for why use `setTimeout` here.

2020-11-16 08:09 UTC, jane-rose commented on src/app/widgets/Console/Terminal.jsx
> +        setTimeout(() => {
> Is it worth removing `.primary-container` and `.secondary-container` from [here](https://github.com/Snapmaker/Luban/blob/78160f6ea26a4667d01d506e29ec757e8b7d3a39/src/app/containers/Workspace/index.styl#L13) as well now since these styles will always be overridden?

yes,u are right

2020-11-16 08:09 UTC, jane-rose commented
> Is it worth removing `.primary-container` and `.secondary-container` from [here](https://github.com/Snapmaker/Luban/blob/78160f6ea26a4667d01d506e29ec757e8b7d3a39/src/app/containers/Workspace/index.styl#L13) as well now since these styles will always be overridden?

yes

2020-11-16 08:25 UTC, merged

2020-11-20 09:35 UTC, jane-rose commented
Fixes #500