Fix: Fix connecting wifi manually bug
Snapmaker/Luban pull request #685
Opened 2021-01-07 03:48 UTC by jane-rose

2021-01-07 04:18 UTC, jane-rose commented
Fixes #640

2021-01-07 13:46 UTC, parachvte requested changes
inappropriate logic implement, changes needed.

2021-01-07 13:46 UTC, parachvte commented on src/app/widgets/Connection/WifiConnection.jsx
> +                        this.props.addSelectedServerToList(server);
Note that we only support **one single** manual server (cause we only save one).
So everytime we call `setSelectedServer()`, the server must be added to server list.

=> `addSelectedServerToList()` action is not necessary, the logic can be put inside of `setSelectedServer()`.

2021-01-07 13:46 UTC, parachvte commented on src/app/flux/machine/action-connect.js
> +const addSelectedServerToList = (server) => (dispatch, getState) => {
The action will cause only `server` present in `servers`, but what we need is prepend selected `server` to server list, not replacing it.

2021-01-08 02:23 UTC, jane-rose commented on src/app/widgets/Connection/WifiConnection.jsx
> +                        this.props.addSelectedServerToList(server);
No, i konw think so.

2021-01-08 02:24 UTC, jane-rose commented on src/app/flux/machine/action-connect.js
> +const addSelectedServerToList = (server) => (dispatch, getState) => {
Yep, that's make sense

2021-01-08 10:13 UTC, merged