Fix: Resize with uniform scale
Snapmaker/Luban pull request #804
Opened 2021-03-01 07:18 UTC by bbaa77770

SB279

2021-03-03 08:48 UTC, meiliang1123 approved these changes
LGTM

2021-03-04 08:17 UTC, parachvte commented on src/app/models/SVGActionsFactory.js
> +    /**
Comment without any information.

2021-03-04 08:18 UTC, parachvte commented on src/app/models/SVGActionsFactory.js
> +    /**
Comment without any information.

2021-03-04 08:48 UTC, parachvte commented on src/app/models/SVGActionsFactory.js
> +    getSelectedElementsUniformScalingState() {
Unwanted method position.

2021-03-04 08:51 UTC, parachvte commented on src/app/models/SvgModel.js
> +            const sourceWidth = width * Math.abs(scaleX) * DEFAULT_SCALE;
Add comment for `DEFAULT_SCALE`, it's a temporary solution.

2021-03-04 08:54 UTC, parachvte requested changes
More comment requested.

2021-03-04 09:41 UTC, parachvte approved these changes

2021-03-04 09:43 UTC, merged