Fix: Change i18n config and update translations
Snapmaker/Luban pull request #851
Opened 2021-03-10 20:28 UTC by bbaa77770

2021-03-11 03:54 UTC, parachvte requested changes
Keep up i18n key convention with @voidrin

2021-03-11 08:50 UTC, voidrin commented
# About Resource Naming Convention

String keys can be naming by this following convention:

`<WHAT>_<WHERE>_<DESCRIPTION>`

As the string keys naming, I recommend to be connected by hyphen(not sure hyphen is permitted) or underscore instead of empty space.

### Advantages
- ordering the resource
- better readability and logically
- avoid naming conflict

### Disadvantages
- hard to refactor
- need to describe it clearly

## Examples
### Good
`laser_camera_aid_background_instructions_step1`

###  Not Good
`instructions of laser camera steps 1 1`
`instructions_laser_camera_4`

2021-03-11 10:34 UTC, parachvte commented on src/app/config/settings.js
> +        keySeparator: ' ',
false?

2021-03-12 02:13 UTC, merged

2021-03-12 02:54 UTC, parachvte commented
LU-408 Updates i18n copy

2021-03-12 02:55 UTC, parachvte commented
LU-408 Updates i18n copy