Improvement: Disable multi-select models of different toolpath types
Snapmaker/Luban pull request #894
Opened 2021-03-24 02:33 UTC by meiliang1123

2021-03-24 02:33 UTC, meiliang1123 commented
LU-709

2021-03-29 09:10 UTC, parachvte requested changes
- style import changes required
- component wrapper recommended
- improvement approved

2021-03-29 09:10 UTC, parachvte commented on src/app/containers/App.jsx
> +import '../styles/react-toastify.styl';
Checkout `src/app/styles/vendor.styl`, this is how we add vendor style.

2021-03-29 09:10 UTC, parachvte commented on src/app/containers/App.jsx
> +                {/* https://fkhadra.github.io/react-toastify/api/toast-container */}
Doc about 3rd party React Component is not needed (and not recommended cuz no information for later use).

Recommended way to do this is to wrapper 3rd party component, and then add docs on wrapped component. :)

2021-03-30 08:07 UTC, merged