Refactor: Replace class to hooks on object list component
Snapmaker/Luban pull request #917
Opened 2021-04-09 10:24 UTC by jane-rose

2021-04-09 10:50 UTC, parachvte commented on src/app/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
> +    const models = useSelector(state => state[props.headType].modelGroup && state[props.headType].modelGroup.models);
Check properties correctly.

2021-04-12 02:40 UTC, jane-rose commented on src/app/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
> +    const models = useSelector(state => state[props.headType].modelGroup && state[props.headType].modelGroup.models);
Updated @parachvte

2021-04-12 03:44 UTC, parachvte commented on src/app/lib/redux-select.js
> +export const reduxSelector = (allState, attributeArray) => {
getAttribute(object, attributePath) {

}

2021-04-26 13:01 UTC, parachvte commented on src/app/flux/editor/actions-process.js
> +        console.log('saveToolPath', toolPath);
Remember to remove log.

2021-05-11 06:14 UTC, meiliang1123 requested changes

2021-05-11 06:14 UTC, meiliang1123 commented on src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
> +                console.log('_processImage', img, this.modelPath);
logs

2021-05-11 07:10 UTC, parachvte commented on src/app/rehooks/widget-title.jsx
> +const useWidgetTitle = (setTitle, title, otherFunction) => {
Not being used?

2021-05-11 08:15 UTC, meiliang1123 approved these changes

2021-05-12 10:40 UTC, merged