Improvement: Add top-right in Cnc and Laser canvas
Snapmaker/Luban pull request #918
Opened 2021-04-09 14:40 UTC by bbaa77770

LU-714

2021-04-12 06:26 UTC, parachvte commented on src/app/toolpaths/ToolPathGroup.js
> +        this.toolPathObjects.visible = show;
`this.toolPathObjects` is nullable?

2021-04-12 06:28 UTC, parachvte commented on src/app/toolpaths/ToolPathGroup.js
> +        this.toolPathObjects.visible = show;
`showToolpathObjects` uses objects
`showSimulationObject` uses object, there are `this.simulationObjects` and `this.simulationObject`, what's the differences?

2021-04-12 06:30 UTC, parachvte commented on src/app/widgets/CncLaserTopRight/styles.styl
> +.visualizer-top-right
Use { braces

2021-04-12 06:31 UTC, parachvte commented on src/app/widgets/LaserVisualizer/Visualizer.jsx
> +                {(!isEditor && displayedType === 'toolpath') && (
`DISPLAYED_TYPE_TOOLPATH`

2021-04-12 06:33 UTC, parachvte requested changes
Check procedure before merging PR.

2021-04-12 08:41 UTC, zjiefee approved these changes

2021-04-13 03:55 UTC, parachvte approved these changes

2021-04-13 04:01 UTC, merged