Refactor: Add shortcut manager to replace shortcut callbacks in flux
Snapmaker/Luban pull request #999
Opened 2021-05-13 02:27 UTC by meiliang1123

- removed some old shortcuts

2021-05-14 02:40 UTC, parachvte commented on src/app/containers/App.jsx
> +     *  */
**/

2021-05-14 02:54 UTC, parachvte commented on src/app/flux/printing/index.js
> +    offsetGcodeLayers: (offset) => (dispatch, getState) => {
If only `offsetGcodeLayers(1)` and `offsetGcodeLayers(-1)` are used, I would prefer ~~`nextLayer()` and `previousLayer()`.~~ `upperLayer()` and `lowerLayer()`, only 2 functions exposed.

2021-05-14 02:55 UTC, parachvte commented on src/app/flux/printing/index.js
> +    offsetGcodeLayers: (offset) => (dispatch, getState) => {
If use `offsetGcodeLayers()`, better it being documented.

2021-05-14 02:56 UTC, parachvte commented on src/app/lib/shortcut/manager.js
> +    _comboKeyCallbackMap={};
make sure to run ESLint before you commit.

2021-05-14 02:58 UTC, parachvte commented on src/app/lib/shortcut/manager.js
> +        if (!(responder.priority in Object.values(priorities))) {
- Check if responder is null
- Check all properties required, `title`? `shortcuts`? and check type of shortcut function

2021-05-14 02:59 UTC, parachvte commented on src/app/lib/shortcut/manager.js
> +        this._responders.sort((a, b) => a.priority - b.priority);
Add a comment above to indicate responders are sorted by priority (low to high or high to low)

2021-05-14 03:01 UTC, parachvte commented on src/app/lib/shortcut/manager.js
> +            if (titles.indexOf(responder.title) === -1) {
- So title is the unique key for responders?
- Maybe rename `responder` to `shortcutHandler`, it's way more easier to understand and remember.

2021-05-14 03:16 UTC, parachvte requested changes
- Only add withRouter once, and convert `ownProps.location.pathname` to the page name (constant) in redux state. Watch redux page state in component if needed.
- Use method below to define responder. Here we want to avoid using enclosure, because it's NOT friendly to semantic analysis (ESLint checking).

```JS
class Visualizer extends PureComponent {
    shortcutResponder = {
        title: this.constructor.name,
        active: this.active,
    };

    get active() {
        return this.isActive;
    }
}
```

2021-05-14 03:32 UTC, parachvte commented on src/app/lib/shortcut/manager.js
> +                console.log(`${responder.title}-P${responder.priority} ${actionName} [${comboKeys.join(' , ')}]`);
remove log

2021-05-14 03:35 UTC, parachvte commented on src/app/lib/shortcut/manager.js
> +            let mapItem = this._comboKeyCallbackMap[comboKey];
```JS
if (!this._comboKeyCallbackMap[comboKey]) {
    this._comboKeyCallbackMap[comboKey] = [];
}
const mapItem = this._comboKeyCallbackMap[comboKey];
```

2021-05-14 08:43 UTC, meiliang1123 commented on src/app/flux/printing/index.js
> +    offsetGcodeLayers: (offset) => (dispatch, getState) => {
use `offsetGcodeLayers()`  because offset should be set larger if shortcut pressed rapidly.

2021-05-14 08:48 UTC, meiliang1123 commented
> * Only add withRouter once, and convert `ownProps.location.pathname` to the page name (constant) in redux state. Watch redux page state in component if needed.
> * Use method below to define responder. Here we want to avoid using enclosure, because it's NOT friendly to semantic analysis (ESLint checking).
> 
> ```js
> class Visualizer extends PureComponent {
>     shortcutResponder = {
>         title: this.constructor.name,
>         active: this.active,
>     };
> 
>     get active() {
>         return this.isActive;
>     }
> }
> ```

good code! thanks!

2021-05-24 03:41 UTC, meiliang1123 commented on src/app/lib/shortcut/manager.js
> +            if (titles.indexOf(responder.title) === -1) {
title is just for printing, not the unique key for shortcut manger

2021-05-25 07:51 UTC, merged